/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/estandares-aplicables/calculo": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["EstandaresController_calcular"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/organizaciones": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["OrganizacionesController_listar"]
    put?: never
    post: operations["OrganizacionesController_registrar"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/organizaciones/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["OrganizacionesController_obtener"]
    put: operations["OrganizacionesController_corregir"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/organizaciones/{id}/reenvio": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["OrganizacionesController_reenviar"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/admin/organizaciones/validacion": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["AdminValidacionController_cola"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/admin/organizaciones/{id}/aprobacion": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["AdminValidacionController_aprobar"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/admin/organizaciones/{id}/devolucion": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["AdminValidacionController_devolver"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/catalogos/departamentos": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["CatalogosController_departamentos"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/catalogos/departamentos/{codigo}/municipios": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["CatalogosController_municipios"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/catalogos/ciiu": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["CatalogosController_ciiu"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/catalogos/arl": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["CatalogosController_arl"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    SedeRiesgoDto: {
      /**
       * @example III
       * @enum {string}
       */
      claseRiesgo: "I" | "II" | "III" | "IV" | "V"
      /** @example 12 */
      trabajadores: number
    }
    CalculoEstandaresDto: {
      sedes: components["schemas"]["SedeRiesgoDto"][]
    }
    EstandaresAplicablesDto: {
      /**
       * @example 21
       * @enum {number}
       */
      estandares: 7 | 21 | 62
      /**
       * @example III
       * @enum {string}
       */
      riesgoMaximo: "I" | "II" | "III" | "IV" | "V"
      /** @example 12 */
      totalTrabajadores: number
      /** @example Entre 11 y 50 trabajadores con riesgo máximo I, II o III */
      regla: string
    }
    SedeDto: {
      /** @example Oficina principal */
      nombre: string
      /** @example Calle 36 # 27-52 */
      direccion: string
      /**
       * @description Código DANE (DIVIPOLA)
       * @example 68
       */
      departamentoCodigo: string
      /**
       * @description Código DANE (DIVIPOLA)
       * @example 68001
       */
      municipioCodigo: string
      /**
       * @example II
       * @enum {string}
       */
      claseRiesgo: "I" | "II" | "III" | "IV" | "V"
      /** @example 12 */
      trabajadores: number
      /**
       * @description Código CIIU
       * @example 6201
       */
      ciiuCodigo: string
    }
    RegistrarOrganizacionDto: {
      /** @example Sistemas y Computadores S.A. */
      razonSocial: string
      /** @example SYC */
      nombreComercial?: string
      /**
       * @example JURIDICA
       * @enum {string}
       */
      tipoPersona: "JURIDICA" | "NATURAL"
      /**
       * @description Solo dígitos, sin DV
       * @example 800197268
       */
      nit: string
      /** @example 4 */
      digitoVerificacion: string
      /** @example Nombre del representante legal */
      repLegalNombre: string
      /** @enum {string} */
      repLegalTipoDoc?: "CC" | "CE" | "PASAPORTE"
      /** @example 1234567 */
      repLegalNumeroDoc?: string
      /**
       * @description Código del catálogo de ARL
       * @example aurora
       */
      arlCodigo?: string
      sedes: components["schemas"]["SedeDto"][]
    }
    SedeRegistradaDto: {
      /** @example Oficina principal */
      nombre: string
      /** @example Calle 36 # 27-52 */
      direccion: string
      /**
       * @description Código DANE (DIVIPOLA)
       * @example 68
       */
      departamentoCodigo: string
      /**
       * @description Código DANE (DIVIPOLA)
       * @example 68001
       */
      municipioCodigo: string
      /**
       * @example II
       * @enum {string}
       */
      claseRiesgo: "I" | "II" | "III" | "IV" | "V"
      /** @example 12 */
      trabajadores: number
      /**
       * @description Código CIIU
       * @example 6201
       */
      ciiuCodigo: string
      /** Format: uuid */
      id: string
    }
    OrganizacionDto: {
      /** Format: uuid */
      id: string
      razonSocial: string
      nombreComercial: string | null
      /** @description Nombre comercial o, si falta, la razón social (R1.8) */
      nombreVisible: string
      /** @enum {string} */
      tipoPersona: "JURIDICA" | "NATURAL"
      nit: string
      digitoVerificacion: string
      repLegalNombre: string
      /** @enum {string|null} */
      repLegalTipoDoc: "CC" | "CE" | "PASAPORTE" | null
      repLegalNumeroDoc: string | null
      arlCodigo: string | null
      /** @enum {string} */
      estado: "EN_VALIDACION" | "DEVUELTA" | "APROBADA"
      motivoDevolucion: string | null
      /** Format: date-time */
      enviadaEn: string
      /** @enum {string} */
      riesgoMaximo: "I" | "II" | "III" | "IV" | "V"
      totalTrabajadores: number
      /** @enum {number} */
      estandaresAplicables: 7 | 21 | 62
      sedes: components["schemas"]["SedeRegistradaDto"][]
    }
    ArlDto: {
      /** @example aurora */
      codigo: string
      /** @example Aurora */
      nombre: string
    }
    TarjetaOrganizacionDto: {
      /** Format: uuid */
      id: string
      /** @description Nombre comercial o razón social (R1.8) */
      nombreVisible: string
      /** @enum {string} */
      estado: "EN_VALIDACION" | "DEVUELTA" | "APROBADA"
      /** @enum {string} */
      riesgoMaximo: "I" | "II" | "III" | "IV" | "V"
      arl: components["schemas"]["ArlDto"] | null
      totalTrabajadores: number
      /** @enum {number} */
      estandaresAplicables: 7 | 21 | 62
      /** @description null = Sin evaluar mientras D2 esté en MOCK (R5.3) */
      porcentajeImplementacion: number | null
      /** @description Ídem (R5.3) */
      porcentajeCumplimiento: number | null
      /** @description Solo true si está Aprobada (R5.4, DEC-12) */
      puedeIngresar: boolean
      /** @description Solo si está Devuelta (R5.5) */
      motivoDevolucion: string | null
    }
    ListaOrganizacionesDto: {
      /** @description Organizaciones del usuario (R5.7) */
      total: number
      organizaciones: components["schemas"]["TarjetaOrganizacionDto"][]
    }
    CasoValidacionDto: {
      /** Format: uuid */
      id: string
      nombreVisible: string
      razonSocial: string
      nit: string
      digitoVerificacion: string
      /** Format: date-time */
      enviadaEn: string
      /** @enum {string} */
      riesgoMaximo: "I" | "II" | "III" | "IV" | "V"
      totalTrabajadores: number
      /** @enum {number} */
      estandaresAplicables: 7 | 21 | 62
      /** @description Número de sedes */
      sedes: number
    }
    DevolucionDto: {
      /** @example El RUT no corresponde a la razón social */
      motivo: string
    }
    DepartamentoDto: {
      /** @example 68 */
      codigo: string
      /** @example SANTANDER */
      nombre: string
    }
    MunicipioDto: {
      /** @example 68679 */
      codigo: string
      /** @example SAN GIL */
      nombre: string
    }
    ActividadCiiuDto: {
      /** @example 6201 */
      codigo: string
      /** @example Actividades de desarrollo de sistemas informáticos */
      descripcion: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  EstandaresController_calcular: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CalculoEstandaresDto"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["EstandaresAplicablesDto"]
        }
      }
    }
  }
  OrganizacionesController_listar: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ListaOrganizacionesDto"]
        }
      }
    }
  }
  OrganizacionesController_registrar: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegistrarOrganizacionDto"]
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["OrganizacionDto"]
        }
      }
      /** @description Campos inválidos en errores[].campo */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description El NIT ya está registrado (R1.7) */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  OrganizacionesController_obtener: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["OrganizacionDto"]
        }
      }
      /** @description No existe o no es del usuario (R6.1) */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  OrganizacionesController_corregir: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegistrarOrganizacionDto"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["OrganizacionDto"]
        }
      }
      /** @description Campos inválidos en errores[].campo */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Solo el Líder SST corrige (R4.6) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description No existe o no es del usuario (R6.1) */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description No está Devuelta (R4.8) o NIT registrado */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  OrganizacionesController_reenviar: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["OrganizacionDto"]
        }
      }
      /** @description Solo el Líder SST reenvía (R4.7) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description No existe o no es del usuario (R6.1) */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description No está Devuelta */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AdminValidacionController_cola: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CasoValidacionDto"][]
        }
      }
      /** @description Solo el Administrador de la plataforma (R4.9) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AdminValidacionController_aprobar: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["OrganizacionDto"]
        }
      }
      /** @description Solo el Administrador de la plataforma (R4.9) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description No está En validación (R4.10) */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AdminValidacionController_devolver: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["DevolucionDto"]
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["OrganizacionDto"]
        }
      }
      /** @description Solo el Administrador de la plataforma (R4.9) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description No está En validación (R4.10) */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  CatalogosController_departamentos: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["DepartamentoDto"][]
        }
      }
    }
  }
  CatalogosController_municipios: {
    parameters: {
      query?: never
      header?: never
      path: {
        codigo: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MunicipioDto"][]
        }
      }
    }
  }
  CatalogosController_ciiu: {
    parameters: {
      query?: {
        /** @description Código o palabra de la descripción */
        q?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ActividadCiiuDto"][]
        }
      }
    }
  }
  CatalogosController_arl: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ArlDto"][]
        }
      }
    }
  }
}
